if(DEFINED ENV{X1BOX_IOS_MIN_VERSION} AND NOT "$ENV{X1BOX_IOS_MIN_VERSION}" STREQUAL "")
    set(X1BOX_IOS_MIN_VERSION "$ENV{X1BOX_IOS_MIN_VERSION}")
else()
    set(X1BOX_IOS_MIN_VERSION "17.0")
endif()

set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CMAKE_SYSTEM_NAME iOS)
set(VCPKG_CMAKE_SYSTEM_VERSION "${X1BOX_IOS_MIN_VERSION}")
set(VCPKG_OSX_ARCHITECTURES x86_64)
set(VCPKG_OSX_SYSROOT iphonesimulator)
set(VCPKG_MAKE_BUILD_TRIPLET
    --build=aarch64-apple-darwin
    --host=x86_64-apple-darwin)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_BUILD_TYPE release)
set(VCPKG_DEP_INFO_OVERRIDE_VARS
    "VCPKG_CMAKE_SYSTEM_NAME;VCPKG_CMAKE_SYSTEM_VERSION;VCPKG_OSX_ARCHITECTURES;VCPKG_OSX_SYSROOT")
